### ISSUE TITLE
Perl::Critic test fails

### ISSUE THREAD

**Issue by eserte** [binary-com/perl-Finance-Bitcoin-Feed#2]
See http://www.cpantesters.org/cpan/report/9dd68384-a1fb-11e4-8646-de34e0bfc7aa for a sample fail report.

**Comment by chylli** [comment]
@eserte Thanks very much for your report. I fixed the problems according to my perlcriticrc. But maybe it still cannot pass your perlcritic test. And there is a module that I copied from other author. I cannot edit that module at once. So I deleted the perlcritic test. 

Thanks again.
